default_stages:
  - commit
fail_fast: true
repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.5.0
    hooks:
      - id: reorder-python-imports
  - repo: local
    hooks:
      - id: black
        name: Code formatting
        entry: poetry run black
        language: system
        files: '.*\.py'
      - id: pytest
        name: Tests
        entry: poetry run pytest -vv
        language: system
        files: '.*\.py'
        pass_filenames: false
