@startmindmap

<style>
mindmapDiagram {
    node {
        BackgroundColor lightblue
    }
    :depth(2) {
      BackGroundColor lightcoral
    }
    :depth(4) {
      BackGroundColor lightcoral
    }
    :depth(6) {
      BackGroundColor lightcoral
    }
    :depth(8) {
      BackGroundColor lightcoral
    }
    :depth(10) {
      BackGroundColor lightcoral
    }
}
</style>

* 335.0/1111 [   |   |   ]
** 140.5/224 [   |   |  x]
*** 7.5/30 [  o|   |x  ]
*** 8.5/32 [   |  o|x  ]
*** 21.5/53 [   |   |o x]
*** 34.0/71 [   | o |  x]
**** 7.5/15 [  x| o |x  ]
**** 12.5/21 [   | ox|x  ]
**** 6.5/14 [   | o |x x]
**** 6.0/14 [   | o | xx]
*** 12.0/38 [   |   | ox]
** 73.5/133 [   |   | x ]
*** 9/23 [   |  x|o  ]
*** 12.5/27 [   |o x|   ]
*** 1.0/11 [   |  o| x ]
*** 21.0/39 [   | o | x ]
*** 16.0/33 [   |   | xo]
** 562.0/754 [   | x |   ]
*** 146.0/522 [   | x |  o]
**** 20.5/43 [  o| x |x  ]
**** 78.5/114 [   | xx|o  ]
***** 4/16 [  o|xx |  o]
***** 1/11 [  o|ox | x ]
***** 1/11 [  o| x |ox ]
***** 18.0/35 [   |oxx|o  ]
***** 3/15 [   | xx|oo ]
***** 6.5/20 [   | xx|o o]
**** 85.0/122 [   | x |o x]
***** 22.0/42 [  o| x |x o]
****** 1.0/5 [o o| x |x x]
****** 3/8 [  x|xx |o o]
****** 3/8 [  o|xx |x o]
****** 12.0/16 [  o| xx|x o]
******* 1/4 [o o| xx|x o]
******* 1.5/5 [  x|ox |oxo]
******** 0.5/1 [o x|xx |oox]
******** 3/3 [ oo|xxx|x o]
******** 0/1 [  x|oxx|oxo]
******* 1.0/4 [  o|oxx|x o]
******* 0.5/3 [  o| xx|xoo]
****** 1/5 [  o| x |xxo]
***** 4.5/18 [  o|ox |  x]
***** 0/10 [  o| x |o x]
***** 4/17 [   | xo|x o]
***** 3.0/16 [   | xo|o x]
***** 1.5/13 [   | x |oox]
**** 192.0/243 [   | x | xo]
***** 3/29 [  o| x |ox ]
***** 18.5/61 [   |oxx|  o]
****** 6.0/10 [  o|oxx|x  ]
****** 9.0/13 [  o|oxx| x ]
****** 6.0/10 [  o|oxx|  x]
****** 13.0/16 [   |oxx|x o]
******* 0/3 [  o|xxo|o x]
******* 1.0/4 [ o |oxx|x o]
******** 0.5/1 [ ox|xxo|o x]
******** 2/2 [ ox|ox |xxo]
******** 0.5/1 [ o |oxx|xxo]
******* 2.0/6 [  o|oxx|x o]
******** 1.0/2 [o x|xxo|o x]
******** 1.5/2 [ ox|xx |oxo]
********* 0/1 [o x|xxo|oxo]
********* 0.5/1 [ ox|xxo|oxo]
********** 0.5/1 [oox|xxo|oxx]
******** 1.5/2 [  o|oxx|xxo]
********* 0/1 [o o|oxx|xxo]
********** 1/1 [oox|xxx|oxo]
********* 0.5/1 [ oo|oxx|xxo]
********** 0.5/1 [oox|xxo|oxx]
******* 0/3 [   |oxx|xoo]
****** 8.5/12 [   |oxx| xo]
***** 13.5/50 [   | xx|o o]
****** 2/6 [  x|xx |o o]
****** 3/7 [  o|xx | xo]
****** 0.5/4 [  o| x |xxo]
****** 20/20 [   |xxx|o o]
****** 11.0/13 [   | xx|oxo]
***** 6.5/37 [   | xo|ox ]
***** 6/36 [   | xo| xo]
***** 3.5/30 [   | x |oxo]
*** 46.0/232 [   | x | o ]
**** 50.5/62 [   | xo|x  ]
**** 17.5/29 [   |oxx|   ]
**** 44.0/56 [   | xo| x ]
**** 74.0/85 [   | x | ox]

@endmindmap